const ActionTypes = {
    SET_USERS: "app/actions/SET_USERS"
}
export const REQUEST_STREAMS_PENDING = "REQUEST_STREAMS_PENDING";
export const REQUEST_STREAMS_SUCCESS = "REQUEST_STREAMS_SUCCESS";
export const REQUEST_STREAMS_FAILED = "REQUEST_STREAMS_FAILED";
