
export const REQUEST_STREAMS_PENDING = "REQUEST_STREAMS_PENDING";
export const REQUEST_STREAMS_SUCCESS = "REQUEST_STREAMS_SUCCESS";
export const REQUEST_STREAMS_FAILED = "REQUEST_STREAMS_FAILED";

export const REQUEST_STREAM_PENDING = "REQUEST_STREAM_PENDING";
export const REQUEST_STREAM_SUCCESS = "REQUEST_STREAM_SUCCESS";
export const REQUEST_STREAM_FAILED = "REQUEST_STREAM_FAILED";
